tag @s add xraynotify
tag @s add killauranotify
tag @s add reachnotify
tag @s add noclipnotify
tag @s add nukernotify
tag @s add instabreaknotify
tag @s add blockreachnotify
tag @s add flynotify
tag @s add itemhacknotify
tag @s add miscnotify